language: csharp
solution: RsaKeyDerivation.sln
install:
  - nuget restore RsaKeyDerivation.sln
  - nuget install NUnit.Runners -Version 3.6.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release RsaKeyDerivation.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.6.0/tools/nunit3-console.exe ./RsaKeyDerivation.Test/bin/Release/RsaKeyDerivation.Test.dll