language: csharp
solution: RsaKeyDerivation.sln
install:
  - nuget restore RsaKeyDerivation.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release RsaKeyDerivation.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./RsaKeyDerivation.Test/bin/Release/RsaKeyDerivation.Tests.dll