language: csharp
solution: RsaKeyDerivation.sln
install:
  - nuget restore RsaKeyDerivation.sln
before_install:
  - sudo apt-get install nunit3-console
before_script:
  - nuget restore RsaKeyDerivation.sln
after_script:
  - nunit-console