image: Visual Studio 2015

environment:
  COVERALLS_REPO_TOKEN:
    secure: H6ZjZpllLgrW53uvCAhah4iVUNGeQEmVLOtAaltgmtBeFg+xC48IuAQcMSwYpOO6

before_build:
- nuget restore
build:
  project: RsaKeyDerivation.sln
  verbosity: minimal
test_script:
- ps: >-
    .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:nunit3-console.exe "-targetargs:""RsaKeyDerivation.Test\bin\$env:CONFIGURATION\RsaKeyDerivation.Test.dll"" " -filter:"+[*]*" -output:opencoverCoverage.xml
    $coveralls = (Resolve-Path "packages/coveralls.net.*/tools/csmacnz.coveralls.exe").ToString()
    
    $env:APPVEYOR_BUILD_NUMBER
    
    & $coveralls --opencover -i opencoverCoverage.xml --repoToken $env:COVERALLS_REPO_TOKEN --useRelativePaths --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_BUILD_NUMBER --serviceName appveyor