image: Visual Studio 2015

environment:
  COVERALLS_REPO_TOKEN:
    secure: H6ZjZpllLgrW53uvCAhah4iVUNGeQEmVLOtAaltgmtBeFg+xC48IuAQcMSwYpOO6
before_build:
- nuget restore
build:
  project: RsaKeyDerivation.sln
  verbosity: minimal
after_test:
  - packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"packages\NUnit.ConsoleRunner.3.7.0\tools\nunit3-console.exe" -targetargs:"/domain:single RsaKeyDerivation.Test/bin/debug/RsaKeyDerivation.Test.dll" -output:coverage.xml
  - packages\coveralls.io.1.4.2\tools\coveralls.net.exe --opencover coverage.xml