image: Visual Studio 2015

environment:
  COVERALLS_REPO_TOKEN:
    secure: H6ZjZpllLgrW53uvCAhah4iVUNGeQEmVLOtAaltgmtBeFg+xC48IuAQcMSwYpOO6

before_build:
- nuget restore
- choco install opencover.portable
- choco install codecov

build:
  project: RsaKeyDerivation.sln
  verbosity: minimal
after_test:
  - cmd: .publishTestData.cmd